### PR TITLE
Add bike route data and parking lots for all cities, also add transit map for Montreal

### LINKED ISSUE #56: Add transit layer for Montreal

### LINKED ISSUE #58: Add bicycle path/route/lane data for all new cities

### LINKED ISSUE #62: Add parking data for all new cities

### PR DESCRIPTION
**Pull request by jamaps**
This addresses #58 and #56 

Also adding parking lots here, #62

### CODE REVIEW

**Comment by jamaps** [comment]
@Nate-Wessel - I did have to add lines for each city here to get the parking lots to load

https://github.com/Nate-Wessel/urban-freight/blob/0d61f1473f3f4b65394e7e47251c17940842b6cc/src/Shift/ParkingLots.jsx#L8-L12

I think this should be updated to only look in the city `data.js` files

**Comment by Nate-Wessel** [comment]
Whoops. Looks like I missed the parking component when I was reorganizing the data. I'll fix that.

**Comment by Nate-Wessel** [comment]
Should parking in Halifax be for the regional municipality? It looks like it ends at the smaller old-city boundary.
Bike stuff too it looks like.

**Comment by Nate-Wessel** [comment]
Except for the Halifax boundary issue / question, this all looks good to me!

**Review by Nate-Wessel — APPROVED** [review]

**Comment by jamaps** [comment]
For Halifax, we need to still update its `boundary.topojson` - all my processes use that to clip

**Pull request merged**
