### PR TITLE
Bike lane history

### PR DESCRIPTION
**Pull request by Nate-Wessel**
I'm working toward pulling down historical bike facilities data and mapping it. Step one is to duplicate the procedure we have now for current data so I can better automate it for the past. 

@jamaps I wonder if you can take a look at what I've done here and see if it aligns with how you were classifying bike facilities for the map? It seems that we had [broken things down into five categories](https://github.com/Nate-Wessel/urban-freight/blob/faa6ce6cc9af0ce9c05d36f95675455676227f75/src/data/data-prep-utils/osm-layers.py#L49-L111) indicated by letters (P,T,L,S,O) but that we then [only rendered three categories](https://github.com/Nate-Wessel/urban-freight/blob/faa6ce6cc9af0ce9c05d36f95675455676227f75/src/Shift/index.jsx#L15-L17) by later combining those together before rendering on the map. 

I think I've largely reproduced the effectively tripartite classification, more compactly with a bit of regex. One other difference if that I'm not quite clipping to city boundaries yet. 

https://github.com/Nate-Wessel/urban-freight/blob/839331a27ae9703a6c1360347f1b2ac1bdcf9c66/src/data/data-prep-utils/fetch-osm.mjs#L47-L82

Though somehow the map seems too cluttered so I think I'm still missing something.

### CODE REVIEW

**Comment by jamaps** [comment]
Thanks! I have this flagged, but probably won't be able to get to it until early next week

**Review by jamaps — COMMENTED** [review]
All looks good when building. The classification is basically what I had before (but could be improved, re with tracks maybe). Looks like some of the data has been updated since when last pulled too which is cool.

Am getting an error when running `node fetch-osm.mjs`. I think it's probably timeout thing with the overpass server. I'll investigate

```
fetching data for Toronto (OSM relation/324211)
waiting 30s before next request
fetching data for Montreal (OSM relation/8508277)
undefined:1
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///var/www/html/urban-freight/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBoundary (file:///var/www/html/urban-freight/src/data/data-prep-utils/fetch-osm.mjs:28:19)
    at async file:///var/www/html/urban-freight/src/data/data-prep-utils/fetch-osm.mjs:17:2
```

**Comment by Nate-Wessel** [comment]
If the classification looks good / the same, feel free to merge in. I'll keep working on the data update script, but that won't effect the maps (except for the updated data) until a bit further on.

**Comment by Nate-Wessel** [comment]
That timing is something I'll play with more too - we'll have to once we start requesting a ton of history data.

**Comment by jamaps** [comment]
I'm able to fix the timeout failure, just by adding a delay between the boundary query and the bike feature query

**Pull request merged**
