### PR TITLE
Adding data for Montreal

### PR DESCRIPTION
**Pull request by jamaps**
including the improve charging stations, DA base choropleth, and pick-up points

Made some minor improvements to the census polygon script

Also refreshed, for other cities, the pick-up and charging data reliant on APIs, just in case they've changed

### CODE REVIEW

**Comment by jamaps** [comment]
oops, just realized that I started this branch from the fetch-osm branch rather than master

**Review by Nate-Wessel — APPROVED** [review]
Looks good! Merge when ready

**Comment by Nate-Wessel** [comment]
Montreal has a hell of a lot of charging stations.

**Comment by jamaps** [comment]
Ya so many!

**Pull request merged**
